spring:
  application:
    name: portfolio-app
  datasource:
    url: jdbc:mysql://${DB_HOST}/${DB_DATABASE}?serverTimeZone=America/Bogota
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
twitter:
  config:
    auth-uri: https://api.twitter.com/oauth2/token?grant_type=client_credentials
    users-uri: https://api.twitter.com/2/users/by/username/:username
    time-line-uri: https://api.twitter.com/2/users/:id/tweets
    api-key: ${TWITTER_API_KEY}
    api-secret-key: ${TWITTER_SECRET_API_KEY}
    access-token: ${TWITTER_ACCESS_TOKEN}
    access-token-secret: ${TWITTER_ACCESS_TOKEN_SECRET}
